### ISSUE TITLE
Possibility to delete a Database

### ISSUE THREAD

**Issue by GuidaMarco** [dardino/scacchi-painter#130]
> Engine version: 0.0.1
> Gui version: 0.0.1

### Description
Assuming that "Save database" will finally work, you will then find with a number of Databases on you Local Folder ... there should be an option to "Delete" a database, which I do not currently see among the available options.

### Step to reproduce
Insert here the steps to reproduce

### Expected
Insert here the expected behaviour

### Actual
Insert here the actual behaviour

**Comment by dardino** [comment]
I have decided not to implement the "delete database" feature as the device's file system already possesses the capability to perform this function. However, as of version 0.0.2, it is now possible to add and remove entries from the database.
